# coding: utf-8

"""
    Expenses API

     The Expenses API allows you to manage accounting and expenses information. 

    The version of the OpenAPI document: 0.1
    Contact: developer-access@brex.com
    Created by: https://brex.com
"""

from brex_expenses_python_sdk.paths.v1_expenses_card_expense_id.get import GetById
from brex_expenses_python_sdk.paths.v1_expenses_card.get import List
from brex_expenses_python_sdk.paths.v1_expenses_card_expense_id.put import UpdateExpense
from brex_expenses_python_sdk.apis.tags.card_expenses_api_raw import CardExpensesApiRaw


class CardExpensesApi(
    GetById,
    List,
    UpdateExpense,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: CardExpensesApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = CardExpensesApiRaw(api_client)
