# coding: utf-8

"""
    Expenses API

     The Expenses API allows you to manage accounting and expenses information. 

    The version of the OpenAPI document: 0.1
    Contact: developer-access@brex.com
    Created by: https://brex.com
"""

from brex_expenses_python_sdk.paths.v1_expenses_card_receipt_match.post import CreateNewReceiptMatch
from brex_expenses_python_sdk.apis.tags.receipt_match_api_raw import ReceiptMatchApiRaw


class ReceiptMatchApi(
    CreateNewReceiptMatch,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: ReceiptMatchApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = ReceiptMatchApiRaw(api_client)
